/**
 * Configuration options for the Bugwatch SDK
 */
export interface BugwatchOptions {
  /** Your project's API key */
  apiKey: string;
  /** API endpoint URL (defaults to https://api.bugwatch.dev) */
  endpoint?: string;
  /** Application environment (e.g., 'production', 'staging') */
  environment?: string;
  /** Application release/version */
  release?: string;
  /** Enable debug logging */
  debug?: boolean;
  /** Sample rate for error events (0.0 to 1.0) */
  sampleRate?: number;
  /** Maximum breadcrumbs to capture */
  maxBreadcrumbs?: number;
  /** Tags to attach to all events */
  tags?: Record<string, string>;
  /** User context */
  user?: UserContext;
  /** Before send hook - return null to drop the event */
  beforeSend?: (event: ErrorEvent) => ErrorEvent | null;
  /** Patterns to ignore (matches against error message) */
  ignoreErrors?: (string | RegExp)[];
}

/**
 * User context attached to events
 */
export interface UserContext {
  id?: string;
  email?: string;
  username?: string;
  [key: string]: unknown;
}

/**
 * Stack frame in an error stack trace
 */
export interface StackFrame {
  filename: string;
  function: string;
  lineno: number;
  colno: number;
  context_line?: string;
  pre_context?: string[];
  post_context?: string[];
  in_app: boolean;
}

/**
 * Exception/error information
 */
export interface ExceptionInfo {
  type: string;
  value: string;
  stacktrace: StackFrame[];
}

/**
 * Breadcrumb for tracking events leading to an error
 */
export interface Breadcrumb {
  timestamp: string;
  category: string;
  message: string;
  level?: "debug" | "info" | "warning" | "error";
  data?: Record<string, unknown>;
}

/**
 * Request context for HTTP errors
 */
export interface RequestContext {
  url?: string;
  method?: string;
  headers?: Record<string, string>;
  query_string?: string;
  data?: unknown;
}

/**
 * Runtime information
 */
export interface RuntimeInfo {
  name: string;
  version: string;
}

/**
 * SDK information
 */
export interface SdkInfo {
  name: string;
  version: string;
}

/**
 * The main error event payload sent to the API
 */
export interface ErrorEvent {
  /** Event ID (generated by SDK) */
  event_id: string;
  /** Timestamp in ISO format */
  timestamp: string;
  /** Platform identifier */
  platform: string;
  /** Error level */
  level: "fatal" | "error" | "warning" | "info" | "debug";
  /** Error message */
  message: string;
  /** Exception information */
  exception?: ExceptionInfo;
  /** Breadcrumbs */
  breadcrumbs?: Breadcrumb[];
  /** Tags */
  tags?: Record<string, string>;
  /** Extra context data */
  extra?: Record<string, unknown>;
  /** User context */
  user?: UserContext;
  /** Request context */
  request?: RequestContext;
  /** Application environment */
  environment?: string;
  /** Application release */
  release?: string;
  /** Server name / hostname */
  server_name?: string;
  /** SDK information */
  sdk?: SdkInfo;
  /** Runtime information */
  runtime?: RuntimeInfo;
}

/**
 * Transport interface for sending events
 */
export interface Transport {
  send(event: ErrorEvent): Promise<void>;
}

/**
 * Integration interface for platform-specific functionality
 */
export interface Integration {
  name: string;
  setup(client: BugwatchClient): void;
}

/**
 * Bugwatch client interface
 */
export interface BugwatchClient {
  captureException(error: Error, context?: Partial<ErrorEvent>): string;
  captureMessage(message: string, level?: ErrorEvent["level"]): string;
  addBreadcrumb(breadcrumb: Omit<Breadcrumb, "timestamp">): void;
  setUser(user: UserContext | null): void;
  setTag(key: string, value: string): void;
  setExtra(key: string, value: unknown): void;
  getOptions(): BugwatchOptions;
}
